In [1]:
# installation de libraries
import pandas as pd
import numpy as np
import zipfile

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# l'utilisation du point d'exclamation permet l'exécution de commandes shell dans la machine à laquelle on est connecté
# ici, la fonction installe l'API Kaggle sur la machine
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [4]:
# création d'un répertoire nommé kaggle dans la machine
! mkdir ~/.kaggle

In [5]:
# enregistrez le fichier kaggle.json dans votre drive google. Pour faire simple, je ne l'ai pas mis dans une arboressence
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/kaggle.json

In [6]:
# on demande à l'API kaggle de télécharger le dataset choisi
! kaggle datasets download -d PromptCloudHQ/innerwear-data-from-victorias-secret-and-others -f victoriassecret_com.csv
 # pour plus d'information : https://github.com/Kaggle/kaggle-api

Dataset URL: https://www.kaggle.com/datasets/PromptCloudHQ/innerwear-data-from-victorias-secret-and-others
License(s): CC-BY-SA-4.0
Downloading victoriassecret_com.csv to /content
  0% 0.00/5.65M [00:00<?, ?B/s]
100% 5.65M/5.65M [00:00<00:00, 712MB/s]

In [7]:
# regarder dans l'arborescence de la machine, le fichier téléchargé est en .zip, on peut le décompresser facilement
! unzip victoriassecret_com.csv

Archive:  victoriassecret_com.csv
replace victoriassecret_com.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: victoriassecret_com.csv

In [8]:
# le contenu de la machine est vidé à chaque fois qu'on se déconnecte, il est donc important de bien copier le fichier de travail sur votre drive
# on crée un dossier Data dans notre drive
! mkdir /content/drive/MyDrive/Colab_Notebooks/Data/

mkdir: cannot create directory ‘/content/drive/MyDrive/Colab_Notebooks/Data/’: File exists

In [9]:
# on y copie notre fichier
!cp victoriassecret_com.csv /content/drive/MyDrive/Colab_Notebooks/Data/

# A exécuter

In [ ]:
# installation de libraries
import pandas as pd
import numpy as np
import zipfile

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
%%time
df = pd.read_csv('drive/MyDrive/Colab_Notebooks/Data/victoriassecret_com.csv')

CPU times: user 5.76 s, sys: 545 ms, total: 6.3 s
Wall time: 7.57 s

In [ ]:
def clean_price(s):
    if s[0] == '$':
        return float(s[1:])
    else:
        return None

In [ ]:
df[['mrp','price']] = df[['mrp','price']].applymap(clean_price).astype(float)

<ipython-input-5-18eb6051973e>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[['mrp','price']] = df[['mrp','price']].applymap(clean_price).astype(float)

In [ ]:
medians = df[['mrp','price','rating','review_count']].median()

In [ ]:
df.fillna(value=medians, inplace=True)

# Exploring the data

### I. Load data into pandas dataframe

Here, use the **read_csv method** to load data into pandas dataframe.

Look how it is similar to what we did yesterday regarding the methods into class.

**Note:** Have a look at the pandas doc to understand the read_csv syntax

In [ ]:
%%time
df = pd.read_csv('drive/MyDrive/Colab_Notebooks/Data/victoriassecret_com.csv')

CPU times: user 4.89 s, sys: 433 ms, total: 5.33 s
Wall time: 5.67 s

In [11]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba
1,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black
2,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust
3,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue
4,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white
453382,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape
453383,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink
453384,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white
453385,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape

In [ ]:
len(df)

453386

In [ ]:
### this is what we used to store the data with a convenient delimiter...
#df.to_csv('data/victoria.csv', sep = "*", index = False)

In [ ]:
# Check the type of the df object created
type(df)

pandas.core.frame.DataFrame

In [ ]:
# shift to see properties and methods
# or execute dir(df)
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'available_size',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'brand_name',
 'clip',
 'color',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'description',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mrp',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pdp_url',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'prod',
 'product',
 'product_category',
 'product_name',
 'quantile',
 'query',
 'radd',
 'rank',
 'rating',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'retailer',
 'review_count',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'style_attributes',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'total_sizes',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [ ]:
# shift-tab 1-4 times to show docs
df()

TypeError: 'DataFrame' object is not callable

In [ ]:
len(df)

In [ ]:
# Check the different columns of the df
# Same here: see how similar it is compared to what you already done
df.columns

In [ ]:
df.dtypes

---
Use the method iloc (see the pandas doc) on df. What do you have as output?

In [ ]:
df.iloc[-1]

---
Which method can be used to extract only the X first lines from the csv file?

In [ ]:
df.head(5)
# df.tail(10)

In [ ]:
df.tail(5)

---
Try to extract data from the 'product_name' column.

Remember how we used it when defining __getitem__ in the dataFrame class.

In [ ]:
df['product_name']

----
Use the describe method on df. What kind of output do you get?

In [ ]:
df.describe()

-----
With Pandas, there are also some interesting methods that allow us to identify where you have null values (nan or empty).

Apply isnull and sum methods on df.

What do you get?

In [ ]:
df.isnull().sum()

---
Apply the value_counts() method to df considering the 'price' and 'product_name' columns

In [ ]:
df['price']

In [ ]:
df['price'].value_counts()

In [ ]:
df['product_name'].value_counts()

----------

### II. Preprocess data

#### Step 1:

Convert `price` and `mrp` columns to numerics

First check all the values of 'mrp' and 'price' columns using value_counts().
And save them into new variables.

In [ ]:
df['mrp'].value_counts()

In [ ]:
mrps = df['mrp'].value_counts()
mrps.tail(20) # we've got non USD currencies we'll need to drop

Check for the last values in the value_counts. You can use here the tail method.

In [ ]:
df['mrp'].iloc[i][0]

We can see that the currency is indicated at the beginning of each value.

In order to explore all the distinct currencies in our dataFrame, we pick up every distinct character at index 0 and count them.

In [ ]:
df['mrp']

In [ ]:
text='banane'

In [ ]:
text[0]

In [ ]:
def f(x):
    return x[0]

df['mrp'].apply(f)
#df['mrp'].apply(lambda x : x[0])

In [ ]:
df['mrp'].apply(lambda x: x[0]).value_counts()

---
Now create a function "clean_price" which takes one argument to be this first element.

Then if this element is dollar, extract the rest of the element without the dollar.
Do nothing if not (=put None).

In [ ]:
df[df['mrp']=='Rp543.294']

In [ ]:
def clean_price(s):
    if s[0] == '$':
        return float(s[1:])
    else:
        return None

In [ ]:
df['mrp'].apply(clean_price).astype(float)

In [ ]:

df['price'].apply(clean_price).astype(float)

In [ ]:
price_clean=df['price'].apply(clean_price).astype(float)

In [ ]:
df['price_clean']=price_clean

In [ ]:
df

In [ ]:
df.dtypes

Apply this function to 'mrp' and 'price' columns, using apply.

Here the **apply method** is only valid for a specific column of a dataset.
Use **applymap** if you need to apply a function to 2 or more columns.

In [ ]:
df['mrp'].apply(clean_price).astype(float).isnull().sum()

**Note:**
You need here to also apply the astype method in order to modify the type of the column.

Remember with df.dtypes(), the 'mrp' column was an "object" type (string of characters in fact). Now that we modified the content and extracted the float numbers, we need to convert and certify the new float type of this column.

In [ ]:
df[['mrp','price']]

In [ ]:
df[['mrp','price']].applymap(clean_price).astype(float)

In [ ]:
df[['mrp','price']] = df[['mrp','price']].applymap(clean_price).astype(float)

<ipython-input-15-18eb6051973e>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df[['mrp','price']] = df[['mrp','price']].applymap(clean_price).astype(float)

In [ ]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba
1,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black
2,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust
3,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue
4,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white
453382,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape
453383,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink
453384,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white
453385,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape

In [ ]:
# Apply again the describe method and see what's happening
df.describe()

In [ ]:
df.dtypes

----

#### Step 2:

Fill missing values by columns' medians

In [ ]:
# Check back isnull and sum methods applied to df
# What does it mean?
df.isnull().sum()

In [ ]:
# See here the types of data contained in each mentioned columns
df[['mrp','price','rating','review_count','style_attributes']].dtypes

Apply the **median() method** to df considering the 'mrp', 'price', 'rating', 'review_count' and 'style_attributes' columns.

And put the output into a variable called medians.

In [ ]:
cols = ['mrp','price','rating','review_count','style_attributes']

In [ ]:
df[cols]

In [ ]:
df[cols].median()

In [ ]:
# Apply value_counts to df['style_attributes']. What's happening?
df['style_attributes'].value_counts()

In [ ]:
medians = df[['mrp','price','rating','review_count']].median()
medians

mrp              36.0
price            34.5
rating            4.3
review_count    147.0
dtype: float64

----
The fillna method exists in Pandas.
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html)

Apply this one to the 'mrp', 'price', 'rating' and 'review_count' columns in df, replacing nan values by medians.

Then apply again describe to this.

In [ ]:
df[['mrp','price','rating','review_count']].fillna(value=medians).describe()

Apply fillna to df using inplace = True

In [ ]:
df[['mrp','price','rating','review_count']].fillna(value=medians)

In [ ]:
df.fillna(value=medians, inplace=True)

In [ ]:
df.isnull().sum()

In [ ]:
df.describe()

For further use, let's make a preprocess function

In [ ]:
def preprocess_df(df, clean_fn, cols):
    df[cols] = df[cols].applymap(clean_fn).astype(float)
    medians = df[cols].median()
    df.fillna(value=medians, inplace=True)

In [ ]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba
1,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black
2,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust
3,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue
4,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white
453382,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape
453383,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink
453384,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white
453385,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape

# Data lookup

Let's do again our data exploration made previously, but this time using Pandas methods.

#### Question 1

Which product are the most expensive? what are the indices of the correponding raws and correponding products?

#### Question 2

What are the cheapest products which exists in size 36B? In which colors are they available?

We can do the same, but checking for products for which `total_sizes` contains '36B'

#### Question 3

What are the cheapest 'sport bras'?

#### Question 4
What is the most expensive belt? in which color is it available?

#### Question 5

What is the most common color of the best rated products?

What is then the best rated product available in the most popular color?

# Correction

#### Question 1

Which product are the most expensive? what are the indices of the correponding raws and correponding products?

In [ ]:
df['price'].max()

98.0

In [ ]:
max_price = df['price'].max()

In [ ]:
df.loc[df['price'] == max_price]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
578,Very Sexy Fishnet Lace Kimono,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Fishnet Lace Kimono,Victoriassecret US,"The ultimate lacy layer, with a plunge front a...",4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",XS/S,coconut white
579,Very Sexy Fishnet Lace Kimono,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Fishnet Lace Kimono,Victoriassecret US,"The ultimate lacy layer, with a plunge front a...",4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",M/L,coconut white
22386,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",36C,VS white with nude
22387,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34A,VS white with nude
22388,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34B,VS white with nude
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444135,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32B,VS white with nude
444136,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34D,VS white with nude
444137,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32C,VS white with nude
444138,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32D,VS white with nude
444139,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",36B,VS white with nude

In [ ]:
df.loc[df['price'] == max_price]['product_name'].value_counts()

product_name
Very Sexy NEW! Keyhole Lace Teddy    121
Very Sexy Fishnet Lace Kimono         16
Very Sexy Fishnet Lace Dress           6
Name: count, dtype: int64

#### Question 2

What are the cheapest products which exists in size 36B? In which colors are they available?

In [ ]:
df['available_size'].value_counts()

available_size
S       30458
XS      30189
M       29877
L       29354
XL      16927
34B     15406
32DD    15396
32D     15390
34DD    15352
34C     15282
34D     15079
36C     14853
36B     14753
36D     14551
32B     14439
36DD    14416
32C     14392
32A     12861
34A     12255
38C      9942
38D      9829
38DD     9627
34D3     7891
36D3     7513
36A      7464
32D3     7338
38B      6467
40D      5915
40DD     5892
30C      4804
30B      4709
30A      4693
38D3     4603
40C      4016
34AA     3975
32AA     3928
40D3     2658
36AA      301
XS/S      205
M/L       194
OS        147
D/DD       15
B/C        15
AA/A       15
Name: count, dtype: int64

In [ ]:
df[df['available_size']=='36B']

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
274,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,cadette green
275,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,champagne floral print
276,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,faded denim
277,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,silver sea floral print
278,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,coconut white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453007,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,amethyst logo print
453008,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,cocoon birds of paradise
453009,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dark heather grey
453010,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,midnight tropical
453011,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dazzle

In [ ]:
df['available_size'] == '36B']

In [ ]:
df_1 = df[df['available_size'] == '36B']

In [ ]:
df_1

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
274,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,cadette green
275,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,champagne floral print
276,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,faded denim
277,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,silver sea floral print
278,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,coconut white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453007,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,amethyst logo print
453008,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,cocoon birds of paradise
453009,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dark heather grey
453010,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,midnight tropical
453011,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dazzle

In [ ]:
df_1['price'].min()

5.0

In [ ]:
df_1.loc[df_1['price'] == df_1['price'].min()]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
181575,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Marl
181615,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis Monofilament
181616,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Border Line
181617,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Monofilament
181642,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White Colorblock
181643,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Inkblot Colorblock
181670,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Blocked Curves
181671,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Tinted Plum Mesh Curves
181867,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Firework Texture
181868,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Seychelles
181869,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Rainbow Rings
181870,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Endless Orange
181871,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White
181872,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black
181873,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis
181874,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Geometric
181875,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Sacred Geometry
181876,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Hello Lovely
181877,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Textile Stripe
181878,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Wavy Arrows
181879,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Purple Rapture
181880,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Blue Camo Zebra
181881,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Warm Spraypaint Triangles

In [ ]:
min_price = df_1['price'].min()
min_price

5.0

In [ ]:
df_1.loc[df_1['price'] == min_price]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
181575,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Marl
181615,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis Monofilament
181616,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Border Line
181617,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Monofilament
181642,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White Colorblock
181643,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Inkblot Colorblock
181670,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Blocked Curves
181671,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Tinted Plum Mesh Curves
181867,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Firework Texture
181868,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Seychelles
181869,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Rainbow Rings
181870,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Endless Orange
181871,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White
181872,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black
181873,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis
181874,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Geometric
181875,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Sacred Geometry
181876,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Hello Lovely
181877,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Textile Stripe
181878,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Wavy Arrows
181879,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Purple Rapture
181880,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Blue Camo Zebra
181881,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Warm Spraypaint Triangles

In [ ]:
df_1.loc[df_1['price'] == min_price]['product_name'].value_counts()

product_name
Victoria Sport Lightweight by Victoria Sport Bra    23
Name: count, dtype: int64

In [ ]:
df_1.loc[df_1['price'] == min_price]['color'].value_counts()

color
Black Marl                   1
White                        1
Blue Camo Zebra              1
Purple Rapture               1
Wavy Arrows                  1
Cool Textile Stripe          1
Hello Lovely                 1
Red Sacred Geometry          1
Red Geometric                1
Grey Oasis                   1
Black                        1
Endless Orange               1
Grey Oasis Monofilament      1
Cool Rainbow Rings           1
Seychelles                   1
Firework Texture             1
Tinted Plum Mesh Curves      1
Black Blocked Curves         1
Inkblot Colorblock           1
White Colorblock             1
Black Monofilament           1
Border Line                  1
Warm Spraypaint Triangles    1
Name: count, dtype: int64

We can do the same, but checking for products for which `total_sizes` contains '36B'

In [ ]:
# an example
df['total_sizes'][1000]

In [ ]:
df_2 = df.loc[df['total_sizes'].str.contains('36B', regex=False)]
len(df_2)

In [ ]:
# Counting the same without using Pandas methods
count = 0
for raw in df['total_sizes']:
    if '36B' in raw:
        count += 1
count

In [ ]:
min_price = df_2['price'].min()
df_2.loc[df_2['price'] == min_price]['product_name'].value_counts()

In [ ]:
df_2.loc[df_2['price'] == min_price]['color'].value_counts()

#### Question 3

What are the cheapest 'sport bras'?

In [ ]:
df.loc[df['product_category'].str.contains('Sport Bra',regex=False)]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
34,Victoria Sport NEW! The Player by Victoria Spo...,15.0,15.0,https://www.victoriassecret.com/victorias-secr...,Victoria's Secret,The Player by Victoria Sport Sport Bra,Victoriassecret US,"From cycling to circuit training, this medium-...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,Multi Slasher Stripe
35,Victoria Sport NEW! The Player by Victoria Spo...,15.0,15.0,https://www.victoriassecret.com/victorias-secr...,Victoria's Secret,The Player by Victoria Sport Sport Bra,Victoriassecret US,"From cycling to circuit training, this medium-...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",XL,Multi Slasher Stripe
36,Victoria Sport NEW! The Player by Victoria Spo...,15.0,15.0,https://www.victoriassecret.com/victorias-secr...,Victoria's Secret,The Player by Victoria Sport Sport Bra,Victoriassecret US,"From cycling to circuit training, this medium-...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",XS,Multi Slasher Stripe
37,Victoria Sport NEW! The Player by Victoria Spo...,15.0,15.0,https://www.victoriassecret.com/victorias-secr...,Victoria's Secret,The Player by Victoria Sport Sport Bra,Victoriassecret US,"From cycling to circuit training, this medium-...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,Multi Slasher Stripe
38,Victoria Sport NEW! The Player by Victoria Spo...,15.0,15.0,https://www.victoriassecret.com/victorias-secr...,Victoria's Secret,The Player by Victoria Sport Sport Bra,Victoriassecret US,"From cycling to circuit training, this medium-...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,Multi Slasher Stripe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451870,Victoria Sport The Player by Victoria Sport Pl...,24.5,24.5,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,The Player by Victoria Sport Plunge Sport Bra,Victoriassecret US,"Pro-support, anti-smash: this sport bra teams ...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,Black
451871,Victoria Sport The Player by Victoria Sport Pl...,24.5,24.5,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,The Player by Victoria Sport Plunge Sport Bra,Victoriassecret US,"Pro-support, anti-smash: this sport bra teams ...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,Ginger Glaze
451872,Victoria Sport The Player by Victoria Sport Pl...,24.5,24.5,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,The Player by Victoria Sport Plunge Sport Bra,Victoriassecret US,"Pro-support, anti-smash: this sport bra teams ...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,Tinted Plum
451873,Victoria Sport The Player by Victoria Sport Pl...,24.5,24.5,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,The Player by Victoria Sport Plunge Sport Bra,Victoriassecret US,"Pro-support, anti-smash: this sport bra teams ...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,White
451874,Victoria Sport The Player by Victoria Sport Pl...,24.5,24.5,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,The Player by Victoria Sport Plunge Sport Bra,Victoriassecret US,"Pro-support, anti-smash: this sport bra teams ...",4.3,147.0,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,Black

In [ ]:
df_3 = df.loc[df['product_category'].str.contains('Sport Bra',regex=False)]
len(df_3)

62769

In [ ]:
df_3['price'].min()

5.0

In [ ]:
min_price = df_3['price'].min()
df_3.loc[df_3['price'] == min_price]['product_name'].value_counts()

product_name
Victoria Sport Lightweight by Victoria Sport Bra    320
Victoria Sport Strappy Triangle Sport Bra           277
The Player Lace-Up Sport Bra                         61
Name: count, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'Victoria Sport Lightweight by Victoria Sport Bra')
        ]['color'].value_counts()

color
Black Marl                   14
White                        14
Blue Camo Zebra              14
Purple Rapture               14
Wavy Arrows                  14
Cool Textile Stripe          14
Hello Lovely                 14
Red Sacred Geometry          14
Red Geometric                14
Grey Oasis                   14
Black                        14
Endless Orange               14
Grey Oasis Monofilament      14
Cool Rainbow Rings           14
Seychelles                   14
Firework Texture             14
Tinted Plum Mesh Curves      14
Black Blocked Curves         14
White Colorblock             14
Black Monofilament           14
Border Line                  14
Warm Spraypaint Triangles    14
Inkblot Colorblock           12
Name: count, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'Victoria Sport Strappy Triangle Sport Bra')
        ]['color'].value_counts()

color
Rosy Mauve            32
Black                 32
Grape Soda            32
Inkblot               32
Black/White Stripe    32
Black Marl            32
White                 31
Cadette Green         28
Ginger Glaze          26
Name: count, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'The Player Lace-Up Sport Bra')
        ]['color'].value_counts()

color
Tinted Plum                  10
Rosy Mauve                   10
Laced Arrows                 10
Floral Wave                  10
Summer Blues                  9
Grey Traced Chevron           7
Black/White Blended Swirl     5
Name: count, dtype: int64

#### Question 4
What is the most expensive belt? in which color is it available?

In [ ]:
df_4 = df.loc[df['product_category'].str.contains('belt', regex=False)]
len(df_4)

0

In [ ]:
df_4 = df.loc[df['product_category'].str.contains('Belt', regex=False)]
len(df_4)

2

In [ ]:
df_4

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
293828,Very Sexy Heart Lace Garter Belt,58.0,19.99,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Heart Lace Garter Belt,Victoriassecret US,Queen of hearts: this daring garter belt starr...,4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",XS/S,black hearts print
293829,Very Sexy Heart Lace Garter Belt,58.0,19.99,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Heart Lace Garter Belt,Victoriassecret US,Queen of hearts: this daring garter belt starr...,4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",M/L,black hearts print

#### Question 5

What is the most common color of the best rated products?

What is then the best rated product available in the most popular color?

In [ ]:
top_rating = df['rating'].max()
df_5 = df.loc[df['rating'] == top_rating]
top_rating, len(df_5)

In [ ]:
df_5['product_name'].value_counts()

In [ ]:
df_5['color'].value_counts()

In [ ]:
df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'].value_counts()

In [ ]:
len(df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'])

In [ ]:
top_rating = df['rating'].max()
df_5 = df.loc[df['rating'] == top_rating]
top_rating, len(df_5)

In [ ]:
df_5['product_name'].value_counts()

In [ ]:
df_5['color'].value_counts()

In [ ]:
df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'].value_counts()

In [ ]:
len(df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'])