In [6]:
# installation de libraries
import pandas as pd
import numpy as np
import zipfile

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
# l'utilisation du point d'exclamation permet l'exécution de commandes shell dans la machine à laquelle on est connecté
# ici, la fonction installe l'API Kaggle sur la machine
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [12]:
# création d'un répertoire nommé kaggle dans la machine
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [15]:
# enregistrez le fichier kaggle.json dans votre drive google. Pour faire simple, je ne l'ai pas mis dans une arboressence
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/kaggle.json

In [16]:
# on demande à l'API kaggle de télécharger le dataset choisi
! kaggle datasets download -d PromptCloudHQ/innerwear-data-from-victorias-secret-and-others -f victoriassecret_com.csv
 # pour plus d'information : https://github.com/Kaggle/kaggle-api

Downloading victoriassecret_com.csv.zip to /content
  0% 0.00/5.65M [00:00<?, ?B/s]
100% 5.65M/5.65M [00:00<00:00, 63.0MB/s]

In [ ]:
# ! kaggle competitions download -c nfl-player-contact-detection

Downloading nfl-player-contact-detection.zip to /content
  5% 180M/3.84G [00:08<02:48, 23.3MB/s]
User cancelled operation

In [17]:
# regarder dans l'arborescence de la machine, le fichier téléchargé est en .zip, on peut le décompresser facilement
! unzip victoriassecret_com.csv

Archive:  victoriassecret_com.csv.zip
  inflating: victoriassecret_com.csv

In [22]:
# le contenu de la machine est vidé à chaque fois qu'on se déconnecte, il est donc important de bien copier le fichier de travail sur votre drive
# on crée un dossier Data dans notre drive
! mkdir /content/drive/MyDrive/Colab_Notebooks/Data/

mkdir: cannot create directory ‘/content/drive/MyDrive/Colab_Notebooks/Data/’: File exists

In [23]:
# on y copie notre fichier
!cp victoriassecret_com.csv /content/drive/MyDrive/Colab_Notebooks/Data/

# Exploring the data

### I. Load data into pandas dataframe

Here, use the **read_csv method** to load data into pandas dataframe.

Look how it is similar to what we did yesterday regarding the methods into class.

**Note:** Have a look at the pandas doc to understand the read_csv syntax

In [ ]:
### Only necessary if your files are still zipped
# unzip_file('data/victoriassecret_com.csv.zip')

In [ ]:
%%time
df = pd.read_csv('drive/MyDrive/Colab_Notebooks/Data/victoriassecret_com.csv')

CPU times: user 3.94 s, sys: 340 ms, total: 4.28 s
Wall time: 4.75 s

In [ ]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba
1,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black
2,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust
3,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue
4,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white
453382,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape
453383,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink
453384,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white
453385,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape

In [ ]:
len(df)

453386

In [ ]:
### this is what we used to store the data with a convenient delimiter...
#df.to_csv('data/victoria.csv', sep = "*", index = False)

In [ ]:
# Check the type of the df object created
type(df)

pandas.core.frame.DataFrame

In [ ]:
# shift to see properties and methods
# or execute dir(df)
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'available_size',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'brand_name',
 'clip',
 'color',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'description',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mrp',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pdp_url',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'price',
 'prod',
 'product',
 'product_category',
 'product_name',
 'quantile',
 'query',
 'radd',
 'rank',
 'rating',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'retailer',
 'review_count',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'style_attributes',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'total_sizes',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [ ]:
# shift-tab 1-4 times to show docs
df()

TypeError: ignored

In [ ]:
len(df)

453386

In [ ]:
# Check the different columns of the df
# Same here: see how similar it is compared to what you already done
df.columns

Index(['product_name', 'mrp', 'price', 'pdp_url', 'brand_name',
       'product_category', 'retailer', 'description', 'rating', 'review_count',
       'style_attributes', 'total_sizes', 'available_size', 'color'],
      dtype='object')

In [ ]:
df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes    float64
total_sizes          object
available_size       object
color                object
dtype: object

---
Use the method iloc (see the pandas doc) on df. What do you have as output?

In [ ]:
df.iloc[-1]

product_name                         Dream Angels NEW! Lace Mini Slip
mrp                                                           $48.00
price                                                         $48.00
pdp_url             https://www.victoriassecret.com/lingerie/shop-...
brand_name                                          Victoria's Secret
product_category                                       Lace Mini Slip
retailer                                           Victoriassecret US
description         All you need is a little lace, here in the cut...
rating                                                            NaN
review_count                                                      NaN
style_attributes                                                  NaN
total_sizes                               ["XS", "S", "M", "L", "XL"]
available_size                                                      M
color                                                    mulled grape
Name: 453385, dtype: object

---
Which method can be used to extract only the X first lines from the csv file?

In [ ]:
df.head(5)
# df.tail(10)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
0,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba
1,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black
2,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust
3,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue
4,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid

In [ ]:
df.tail(5)

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
453381,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white
453382,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape
453383,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink
453384,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white
453385,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape

---
Try to extract data from the 'product_name' column.

Remember how we used it when defining __getitem__ in the dataFrame class.

In [ ]:
df['product_name']

0         Very Sexy Strappy Lace Thong Panty
1         Very Sexy Strappy Lace Thong Panty
2         Very Sexy Strappy Lace Thong Panty
3         Very Sexy Strappy Lace Thong Panty
4         Very Sexy Strappy Lace Thong Panty
                         ...
453381      Dream Angels NEW! Lace Mini Slip
453382      Dream Angels NEW! Lace Mini Slip
453383      Dream Angels NEW! Lace Mini Slip
453384      Dream Angels NEW! Lace Mini Slip
453385      Dream Angels NEW! Lace Mini Slip
Name: product_name, Length: 453386, dtype: object

----
Use the describe method on df. What kind of output do you get?

In [ ]:
df.describe()

              rating  review_count  style_attributes
count  137734.000000  1.377340e+05               0.0
mean        4.165819  9.202884e+35               NaN
std         0.487524  1.162929e+37               NaN
min         0.000000  2.000000e+00               NaN
25%         4.000000  3.900000e+01               NaN
50%         4.300000  1.470000e+02               NaN
75%         4.500000  4.100000e+02               NaN
max         5.000000  1.560000e+38               NaN

-----
With Pandas, there are also some interesting methods that allow us to identify where you have null values (nan or empty).

Apply isnull and sum methods on df.

What do you get?

In [ ]:
df.isnull().sum()

product_name             0
mrp                      0
price                    0
pdp_url                  0
brand_name               0
product_category         0
retailer                 0
description              0
rating              315652
review_count        315652
style_attributes    453386
total_sizes              0
available_size           0
color                    0
dtype: int64

---
Apply the value_counts() method to df considering the 'price' and 'product_name' columns

In [ ]:
df['price']

0         $14.50
1         $14.50
2         $14.50
3         $14.50
4         $14.50
           ...
453381    $48.00
453382    $48.00
453383    $48.00
453384    $48.00
453385    $48.00
Name: price, Length: 453386, dtype: object

In [ ]:
df['price'].value_counts()

$10.50     45832
$36.50     33365
$34.50     24636
$34.95     24148
$19.99     22784
           ...
$16.95        24
$32.99        12
$64.95        12
$59.95        12
$9.95         11
Name: price, Length: 96, dtype: int64

In [ ]:
df['product_name'].value_counts()

Body by Victoria Perfect Coverage Bra              17922
Victoria Sport Incredible by Victoria Sport Bra    12274
Dream Angels Push-Up Bra                           11878
Very Sexy Push-Up Bra                              10985
Body by Victoria Demi Bra                          10881
                                                   ...
Very Sexy XO Lace Bodysuit                             5
Very Sexy Embroidered Triangle Bra                     4
PINK Fresh & Clean Gym Kit                             3
PINK Coconut Waters Travel Kit                         3
Very Sexy Heart Lace Garter Belt                       2
Name: product_name, Length: 617, dtype: int64

----------

### II. Preprocess data

#### Step 1:

Convert `price` and `mrp` columns to numerics

First check all the values of 'mrp' and 'price' columns using value_counts().
And save them into new variables.

In [ ]:
df['mrp'].value_counts()

$10.50     48627
$36.50     45968
$34.50     35026
$34.95     26374
$54.50     23152
           ...
$24.00        29
$12.95        29
$16.95        24
$64.95        12
$9.95         11
Name: mrp, Length: 78, dtype: int64

In [ ]:
mrps = df['mrp'].value_counts()
mrps.tail(20) # we've got non USD currencies we'll need to drop

$26.50       169
$69.50       168
$98.00       149
Rp474.522    144
$28.95       120
₡24.769      102
Rp543.294     90
$34.00        72
$62.00        63
$48.95        63
Rp116.911     62
$27.95        57
Rp721.448     54
$59.95        54
₡25.935       54
$24.00        29
$12.95        29
$16.95        24
$64.95        12
$9.95         11
Name: mrp, dtype: int64

Check for the last values in the value_counts. You can use here the tail method.

In [ ]:
df['mrp'].iloc[i][0]

NameError: ignored

We can see that the currency is indicated at the beginning of each value.

In order to explore all the distinct currencies in our dataFrame, we pick up every distinct character at index 0 and count them.

In [ ]:
df['mrp']

0         $14.50
1         $14.50
2         $14.50
3         $14.50
4         $14.50
           ...
453381    $48.00
453382    $48.00
453383    $48.00
453384    $48.00
453385    $48.00
Name: mrp, Length: 453386, dtype: object

In [ ]:
text='banane'

In [ ]:
text[0]

'b'

In [ ]:
def f(x):
    return x[0]

df['mrp'].apply(f)
#df['mrp'].apply(lambda x : x[0])

0         $
1         $
2         $
3         $
4         $
         ..
453381    $
453382    $
453383    $
453384    $
453385    $
Name: mrp, Length: 453386, dtype: object

In [ ]:
df['mrp'].apply(lambda x: x[0]).value_counts()

$    452880
R       350
₡       156
Name: mrp, dtype: int64

---
Now create a function "clean_price" which takes one argument to be this first element.

Then if this element is dollar, extract the rest of the element without the dollar.
Do nothing if not (=put None).

In [ ]:
df[df['mrp']=='Rp543.294']

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color
393466,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36C,Pink Ivory Lace
393467,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36C,Lip Smacker Lace
393468,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36C,Black Lace
393469,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36C,Large Paisley Warm Print
393470,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36C,Rosy Mauve Lace
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393639,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36DD,Rosy Mauve Lace
393640,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",38DD,Pink Ivory Lace
393641,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",38DD,Lip Smacker Lace
393642,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",38DD,Large Paisley Warm Print
393643,Easy Push-Up Bra,Rp543.294,Rp543.294,https://www.victoriassecret.com/bralettes/all-...,Victoria's Secret,Easy Push-Up Bra,Victoriassecret US,Like magic: the lift you love without the wire...,4.5,554.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",38DD,Rosy Mauve Lace

In [ ]:
def clean_price(s):
    if s[0] == '$':
        return float(s[1:])
    else:
        return None

In [ ]:
df['mrp'].apply(clean_price).astype(float)

0         14.5
1         14.5
2         14.5
3         14.5
4         14.5
          ...
453381    48.0
453382    48.0
453383    48.0
453384    48.0
453385    48.0
Name: mrp, Length: 453386, dtype: float64

In [ ]:

df['price'].apply(clean_price).astype(float)

0         14.5
1         14.5
2         14.5
3         14.5
4         14.5
          ...
453381    48.0
453382    48.0
453383    48.0
453384    48.0
453385    48.0
Name: price, Length: 453386, dtype: float64

In [ ]:
price_clean=df['price'].apply(clean_price).astype(float)

In [ ]:
df['price_clean']=price_clean

In [ ]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
0,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba,14.5
1,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black,14.5
2,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust,14.5
3,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue,14.5
4,Very Sexy Strappy Lace Thong Panty,$14.50,$14.50,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white,48.0
453382,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape,48.0
453383,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink,48.0
453384,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white,48.0
453385,Dream Angels NEW! Lace Mini Slip,$48.00,$48.00,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape,48.0

In [ ]:
df.dtypes

product_name         object
mrp                  object
price                object
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes    float64
total_sizes          object
available_size       object
color                object
price_clean         float64
dtype: object

Apply this function to 'mrp' and 'price' columns, using apply.

Here the **apply method** is only valid for a specific column of a dataset.
Use **applymap** if you need to apply a function to 2 or more columns.

In [ ]:
df['mrp'].apply(clean_price).astype(float).isnull().sum()

506

**Note:**
You need here to also apply the astype method in order to modify the type of the column.

Remember with df.dtypes(), the 'mrp' column was an "object" type (string of characters in fact). Now that we modified the content and extracted the float numbers, we need to convert and certify the new float type of this column.

In [ ]:
df[['mrp','price']]

            mrp    price
0       $14.50   $14.50
1       $14.50   $14.50
2       $14.50   $14.50
3       $14.50   $14.50
4       $14.50   $14.50
...         ...      ...
453381  $48.00   $48.00
453382  $48.00   $48.00
453383  $48.00   $48.00
453384  $48.00   $48.00
453385  $48.00   $48.00

[453386 rows x 2 columns]

In [ ]:
df[['mrp','price']].applymap(clean_price).astype(float)

         mrp  price
0       14.5   14.5
1       14.5   14.5
2       14.5   14.5
3       14.5   14.5
4       14.5   14.5
...      ...    ...
453381  48.0   48.0
453382  48.0   48.0
453383  48.0   48.0
453384  48.0   48.0
453385  48.0   48.0

[453386 rows x 2 columns]

In [ ]:
df[['mrp','price']] = df[['mrp','price']].applymap(clean_price).astype(float)

In [ ]:
df

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
0,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,peach melba,14.5
1,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,black,14.5
2,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,plum dust,14.5
3,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,ensign blue,14.5
4,Very Sexy Strappy Lace Thong Panty,14.5,14.5,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Strappy Lace Thong Panty,Victoriassecret US,"Lots of cheek peek, pretty lace, a strappy bac...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",S,fair orchid,14.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453381,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,coconut white,48.0
453382,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",L,mulled grape,48.0
453383,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,sheer pink,48.0
453384,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,coconut white,48.0
453385,Dream Angels NEW! Lace Mini Slip,48.0,48.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Lace Mini Slip,Victoriassecret US,"All you need is a little lace, here in the cut...",NaN,NaN,NaN,"[""XS"", ""S"", ""M"", ""L"", ""XL""]",M,mulled grape,48.0

In [ ]:
# Apply again the describe method and see what's happening
df.describe()

,mrp,price,rating,review_count,style_attributes,price_clean
count,452880.000000,452880.000000,137734.000000,1.377340e+05,0.0,452880.000000
mean,36.028995,32.338643,4.165819,9.202884e+35,NaN,32.338643
std,14.762885,15.657394,0.487524,1.162929e+37,NaN,15.657394
min,8.500000,2.990000,0.000000,2.000000e+00,NaN,2.990000
25%,29.500000,19.990000,4.000000,3.900000e+01,NaN,19.990000
50%,36.000000,34.500000,4.300000,1.470000e+02,NaN,34.500000
75%,46.500000,42.500000,4.500000,4.100000e+02,NaN,42.500000
max,98.000000,98.000000,5.000000,1.560000e+38,NaN,98.000000

In [ ]:
df.dtypes

product_name         object
mrp                 float64
price               float64
pdp_url              object
brand_name           object
product_category     object
retailer             object
description          object
rating              float64
review_count        float64
style_attributes    float64
total_sizes          object
available_size       object
color                object
price_clean         float64
dtype: object

----

#### Step 2:

Fill missing values by columns' medians

In [ ]:
# Check back isnull and sum methods applied to df
# What does it mean?
df.isnull().sum()

product_name             0
mrp                    506
price                  506
pdp_url                  0
brand_name               0
product_category         0
retailer                 0
description              0
rating              315652
review_count        315652
style_attributes    453386
total_sizes              0
available_size           0
color                    0
price_clean            506
dtype: int64

In [ ]:
# See here the types of data contained in each mentioned columns
df[['mrp','price','rating','review_count','style_attributes']].dtypes

mrp                 float64
price               float64
rating              float64
review_count        float64
style_attributes    float64
dtype: object

Apply the **median() method** to df considering the 'mrp', 'price', 'rating', 'review_count' and 'style_attributes' columns.

And put the output into a variable called medians.

In [ ]:
cols = ['mrp','price','rating','review_count','style_attributes']

In [ ]:
df[cols]

         mrp  price  rating  review_count  style_attributes
0       14.5   14.5     NaN           NaN               NaN
1       14.5   14.5     NaN           NaN               NaN
2       14.5   14.5     NaN           NaN               NaN
3       14.5   14.5     NaN           NaN               NaN
4       14.5   14.5     NaN           NaN               NaN
...      ...    ...     ...           ...               ...
453381  48.0   48.0     NaN           NaN               NaN
453382  48.0   48.0     NaN           NaN               NaN
453383  48.0   48.0     NaN           NaN               NaN
453384  48.0   48.0     NaN           NaN               NaN
453385  48.0   48.0     NaN           NaN               NaN

[453386 rows x 5 columns]

In [ ]:
df[cols].median()

mrp                  36.0
price                34.5
rating                4.3
review_count        147.0
style_attributes      NaN
dtype: float64

In [ ]:
# Apply value_counts to df['style_attributes']. What's happening?
df['style_attributes'].value_counts()

Series([], Name: style_attributes, dtype: int64)

In [ ]:
medians = df[['mrp','price','rating','review_count']].median()
medians

mrp              36.0
price            34.5
rating            4.3
review_count    147.0
dtype: float64

----
The fillna method exists in Pandas.
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html)

Apply this one to the 'mrp', 'price', 'rating' and 'review_count' columns in df, replacing nan values by medians.

Then apply again describe to this.

In [ ]:
yanis.martinet@gmail.com

In [ ]:
df[['mrp','price','rating','review_count']].fillna(value=medians).describe()

                 mrp          price         rating  review_count
count  453386.000000  453386.000000  453386.000000  4.533860e+05
mean       36.028963      32.341055       4.259237  2.795741e+35
std        14.754645      15.648821       0.275703  6.423671e+36
min         8.500000       2.990000       0.000000  2.000000e+00
25%        29.500000      19.990000       4.300000  1.470000e+02
50%        36.000000      34.500000       4.300000  1.470000e+02
75%        46.500000      42.500000       4.300000  1.470000e+02
max        98.000000      98.000000       5.000000  1.560000e+38

Apply fillna to df using inplace = True

In [ ]:
df[['mrp','price','rating','review_count']].fillna(value=medians)

         mrp  price  rating  review_count
0       14.5   14.5     4.3         147.0
1       14.5   14.5     4.3         147.0
2       14.5   14.5     4.3         147.0
3       14.5   14.5     4.3         147.0
4       14.5   14.5     4.3         147.0
...      ...    ...     ...           ...
453381  48.0   48.0     4.3         147.0
453382  48.0   48.0     4.3         147.0
453383  48.0   48.0     4.3         147.0
453384  48.0   48.0     4.3         147.0
453385  48.0   48.0     4.3         147.0

[453386 rows x 4 columns]

In [ ]:
df.fillna(value=medians, inplace=True)

In [ ]:
df.isnull().sum()

product_name             0
mrp                      0
price                    0
pdp_url                  0
brand_name               0
product_category         0
retailer                 0
description              0
rating                   0
review_count             0
style_attributes    453386
total_sizes              0
available_size           0
color                    0
price_clean            506
dtype: int64

In [ ]:
df.describe()

,mrp,price,rating,review_count,style_attributes,price_clean
count,453386.000000,453386.000000,453386.000000,4.533860e+05,0.0,452880.000000
mean,36.028963,32.341055,4.259237,2.795741e+35,NaN,32.338643
std,14.754645,15.648821,0.275703,6.423671e+36,NaN,15.657394
min,8.500000,2.990000,0.000000,2.000000e+00,NaN,2.990000
25%,29.500000,19.990000,4.300000,1.470000e+02,NaN,19.990000
50%,36.000000,34.500000,4.300000,1.470000e+02,NaN,34.500000
75%,46.500000,42.500000,4.300000,1.470000e+02,NaN,42.500000
max,98.000000,98.000000,5.000000,1.560000e+38,NaN,98.000000

For further use, let's make a preprocess function

In [ ]:
def preprocess_df(df, clean_fn, cols):
    df[cols] = df[cols].applymap(clean_fn).astype(float)
    medians = df[cols].median()
    df.fillna(value=medians, inplace=True)

### III. Data lookup

Let's do again our data exploration made previously, but this time using Pandas methods.

#### Question 1

Which product are the most expensive? what are the indices of the correponding raws and correponding products?

#### Question 2

What are the cheapest products which exists in size 36B? In which colors are they available?

We can do the same, but checking for products for which `total_sizes` contains '36B'

#### Question 3

What are the cheapest 'sport bras'?

#### Question 4
What is the most expensive belt? in which color is it available?

#### Question 5

What is the most common color of the best rated products?

What is then the best rated product available in the most popular color?

# Correction

#### Question 1

Which product are the most expensive? what are the indices of the correponding raws and correponding products?

In [ ]:
max_price = df['price'].max()

In [ ]:
df.loc[df['price'] == max_price]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
578,Very Sexy Fishnet Lace Kimono,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Fishnet Lace Kimono,Victoriassecret US,"The ultimate lacy layer, with a plunge front a...",4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",XS/S,coconut white,98.0
579,Very Sexy Fishnet Lace Kimono,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Fishnet Lace Kimono,Victoriassecret US,"The ultimate lacy layer, with a plunge front a...",4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",M/L,coconut white,98.0
22386,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",36C,VS white with nude,98.0
22387,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34A,VS white with nude,98.0
22388,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34B,VS white with nude,98.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444135,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32B,VS white with nude,98.0
444136,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",34D,VS white with nude,98.0
444137,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32C,VS white with nude,98.0
444138,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",32D,VS white with nude,98.0
444139,Very Sexy NEW! Keyhole Lace Teddy,98.0,98.0,https://www.victoriassecret.com/lingerie/shop-...,Victoria's Secret,Keyhole Lace Teddy,Victoriassecret US,Keep taking risks in sheer lace with delicate ...,4.3,147.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""34A"", ""34B"", ""34...",36B,VS white with nude,98.0

In [ ]:
df.loc[df['price'] == max_price]['product_name'].value_counts()

Very Sexy NEW! Keyhole Lace Teddy    121
Very Sexy Fishnet Lace Kimono         16
Very Sexy Fishnet Lace Dress           6
Name: product_name, dtype: int64

#### Question 2

What are the cheapest products which exists in size 36B? In which colors are they available?

In [ ]:
df['available_size'].value_counts()

S       30458
XS      30189
M       29877
L       29354
XL      16927
34B     15406
32DD    15396
32D     15390
34DD    15352
34C     15282
34D     15079
36C     14853
36B     14753
36D     14551
32B     14439
36DD    14416
32C     14392
32A     12861
34A     12255
38C      9942
38D      9829
38DD     9627
34D3     7891
36D3     7513
36A      7464
32D3     7338
38B      6467
40D      5915
40DD     5892
30C      4804
30B      4709
30A      4693
38D3     4603
40C      4016
34AA     3975
32AA     3928
40D3     2658
36AA      301
XS/S      205
M/L       194
OS        147
D/DD       15
B/C        15
AA/A       15
Name: available_size, dtype: int64

In [ ]:
df_1 = df.loc[df['available_size'] == '36B']
df_1

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
274,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,cadette green,19.99
275,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,champagne floral print,19.99
276,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,faded denim,19.99
277,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,silver sea floral print,19.99
278,Body by Victoria Demi Bra,54.50,19.99,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Demi Bra,Victoriassecret US,Sexy comfort and a sleek shape start with low-...,4.3,147.0,NaN,"[""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""30DDD"", ...",36B,coconut white,19.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453007,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,amethyst logo print,34.95
453008,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,cocoon birds of paradise,34.95
453009,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dark heather grey,34.95
453010,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,midnight tropical,34.95
453011,PINK NEW! Wear Everywhere Lightly Lined Bra,34.95,34.95,https://www.victoriassecret.com/pink/panties/w...,Victoria's Secret Pink,Wear Everywhere Lightly Lined Bra,Victoriassecret US,A true wardrobe essential made new with even s...,4.3,147.0,NaN,"[""30AA"", ""30A"", ""30B"", ""30C"", ""30D"", ""30DD"", ""...",36B,dazzle,34.95

In [ ]:
min_price = df_1['price'].min()
min_price

5.0

In [ ]:
df_1.loc[df_1['price'] == min_price]

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
181575,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Marl,5.0
181615,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis Monofilament,5.0
181616,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Border Line,5.0
181617,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Monofilament,5.0
181642,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White Colorblock,5.0
181643,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Inkblot Colorblock,5.0
181670,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black Blocked Curves,5.0
181671,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Tinted Plum Mesh Curves,5.0
181867,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Firework Texture,5.0
181868,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Seychelles,5.0
181869,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Rainbow Rings,5.0
181870,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Endless Orange,5.0
181871,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,White,5.0
181872,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Black,5.0
181873,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Grey Oasis,5.0
181874,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Geometric,5.0
181875,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Red Sacred Geometry,5.0
181876,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Hello Lovely,5.0
181877,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Cool Textile Stripe,5.0
181878,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Wavy Arrows,5.0
181879,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Purple Rapture,5.0
181880,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Blue Camo Zebra,5.0
181881,Victoria Sport Lightweight by Victoria Sport Bra,29.5,5.0,https://www.victoriassecret.com/bras/shop-all-...,Victoria's Secret,Lightweight by Victoria Sport Bra,Victoriassecret US,Our #1 sport bra for a reason: with a supersof...,4.3,402.0,NaN,"[""32A"", ""32B"", ""32C"", ""32D"", ""32DD"", ""34A"", ""3...",36B,Warm Spraypaint Triangles,5.0

In [ ]:
df_1.loc[df_1['price'] == min_price]['product_name'].value_counts()

Victoria Sport Lightweight by Victoria Sport Bra    23
Name: product_name, dtype: int64

In [ ]:
df_1.loc[df_1['price'] == min_price]['color'].value_counts()

Black Marl                   1
White                        1
Blue Camo Zebra              1
Purple Rapture               1
Wavy Arrows                  1
Cool Textile Stripe          1
Hello Lovely                 1
Red Sacred Geometry          1
Red Geometric                1
Grey Oasis                   1
Black                        1
Endless Orange               1
Grey Oasis Monofilament      1
Cool Rainbow Rings           1
Seychelles                   1
Firework Texture             1
Tinted Plum Mesh Curves      1
Black Blocked Curves         1
Inkblot Colorblock           1
White Colorblock             1
Black Monofilament           1
Border Line                  1
Warm Spraypaint Triangles    1
Name: color, dtype: int64

We can do the same, but checking for products for which `total_sizes` contains '36B'

In [ ]:
# an example
df['total_sizes'][1000]

'["30A", "30B", "30C", "30D", "30DD", "30DDD", "32A", "32B", "32C", "32D", "32DD", "32DDD", "34A", "34B", "34C", "34D", "34DD", "34DDD", "36A", "36B", "36C", "36D", "36DD", "36DDD", "38A", "38B", "38C", "38D", "38DD", "38DDD", "40A", "40B", "40C", "40D", "40DD", "40DDD"]'

In [ ]:
df_2 = df.loc[df['total_sizes'].str.contains('36B', regex=False)]
len(df_2)

314963

In [ ]:
# Counting the same without using Pandas methods
count = 0
for raw in df['total_sizes']:
    if '36B' in raw:
        count += 1
count

314963

In [ ]:
min_price = df_2['price'].min()
df_2.loc[df_2['price'] == min_price]['product_name'].value_counts()

Victoria Sport Lightweight by Victoria Sport Bra    320
Name: product_name, dtype: int64

In [ ]:
df_2.loc[df_2['price'] == min_price]['color'].value_counts()

Black Marl                   14
White                        14
Blue Camo Zebra              14
Purple Rapture               14
Wavy Arrows                  14
Cool Textile Stripe          14
Hello Lovely                 14
Red Sacred Geometry          14
Red Geometric                14
Grey Oasis                   14
Black                        14
Endless Orange               14
Grey Oasis Monofilament      14
Cool Rainbow Rings           14
Seychelles                   14
Firework Texture             14
Tinted Plum Mesh Curves      14
Black Blocked Curves         14
White Colorblock             14
Black Monofilament           14
Border Line                  14
Warm Spraypaint Triangles    14
Inkblot Colorblock           12
Name: color, dtype: int64

#### Question 3

What are the cheapest 'sport bras'?

In [ ]:
df_3 = df.loc[df['product_category'].str.contains('Sport Bra',regex=False)]
len(df_3)

62769

In [ ]:
min_price = df_3['price'].min()
df_3.loc[df_3['price'] == min_price]['product_name'].value_counts()

Victoria Sport Lightweight by Victoria Sport Bra    320
Victoria Sport Strappy Triangle Sport Bra           277
The Player Lace-Up Sport Bra                         61
Name: product_name, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'Victoria Sport Lightweight by Victoria Sport Bra')
        ]['color'].value_counts()

Black Marl                   14
White                        14
Blue Camo Zebra              14
Purple Rapture               14
Wavy Arrows                  14
Cool Textile Stripe          14
Hello Lovely                 14
Red Sacred Geometry          14
Red Geometric                14
Grey Oasis                   14
Black                        14
Endless Orange               14
Grey Oasis Monofilament      14
Cool Rainbow Rings           14
Seychelles                   14
Firework Texture             14
Tinted Plum Mesh Curves      14
Black Blocked Curves         14
White Colorblock             14
Black Monofilament           14
Border Line                  14
Warm Spraypaint Triangles    14
Inkblot Colorblock           12
Name: color, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'Victoria Sport Strappy Triangle Sport Bra')
        ]['color'].value_counts()

Rosy Mauve            32
Black                 32
Grape Soda            32
Inkblot               32
Black/White Stripe    32
Black Marl            32
White                 31
Cadette Green         28
Ginger Glaze          26
Name: color, dtype: int64

In [ ]:
df_3.loc[(df_3['price'] == min_price)
         & (df_3['product_name'] == 'The Player Lace-Up Sport Bra')
        ]['color'].value_counts()

Tinted Plum                  10
Rosy Mauve                   10
Laced Arrows                 10
Floral Wave                  10
Summer Blues                  9
Grey Traced Chevron           7
Black/White Blended Swirl     5
Name: color, dtype: int64

#### Question 4
What is the most expensive belt? in which color is it available?

In [ ]:
df_4 = df.loc[df['product_category'].str.contains('belt', regex=False)]
len(df_4)

0

In [ ]:
df_4 = df.loc[df['product_category'].str.contains('Belt', regex=False)]
len(df_4)

2

In [ ]:
df_4

,product_name,mrp,price,pdp_url,brand_name,product_category,retailer,description,rating,review_count,style_attributes,total_sizes,available_size,color,price_clean
293828,Very Sexy Heart Lace Garter Belt,58.0,19.99,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Heart Lace Garter Belt,Victoriassecret US,Queen of hearts: this daring garter belt starr...,4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",XS/S,black hearts print,19.99
293829,Very Sexy Heart Lace Garter Belt,58.0,19.99,https://www.victoriassecret.com/panties/shop-a...,Victoria's Secret,Heart Lace Garter Belt,Victoriassecret US,Queen of hearts: this daring garter belt starr...,4.3,147.0,NaN,"[""XS/S"", ""M/L ""]",M/L,black hearts print,19.99

#### Question 5

What is the most common color of the best rated products?

What is then the best rated product available in the most popular color?

In [ ]:
top_rating = df['rating'].max()
df_5 = df.loc[df['rating'] == top_rating]
top_rating, len(df_5)

(5.0, 1499)

In [ ]:
df_5['product_name'].value_counts()

Victoria Sport NEW! Lightweight by Victoria Sport Strappy Sport Bra    437
Dream Angels Demi Bra                                                  433
Body by Victoria Demi Bra                                              180
Everyday Perfect NEW! Hipster Panty                                     99
Everyday Perfect NEW! Textured Curved-hem Thong Panty                   57
Cotton Lingerie Mesh Thong Panty                                        39
Dream Angels NEW! Lace & Mesh Cheekini Panty                            36
Very Sexy Lace & Mesh Thong Panty                                       33
Dream Angels NEW! Racerback Lace Bodysuit                               30
Very Sexy NEW! Plunge Lace-up Teddy                                     30
Very Sexy Chiffon Cami & Short Set                                      25
Dream Angels Lace-Trim Thong Panty                                      24
Very Sexy NEW! XO V-string Panty                                        21
Very Sexy NEW! Lace-up High-neck Bra                                    20
Very Sexy Satin Cami & Short Set                                        18
PINK NEW! Cropped Raglan Full-Zip                                       16
PINK Coconut Waters Travel Kit                                           1
Name: product_name, dtype: int64

In [ ]:
df_5['color'].value_counts()

Black                              122
Grey Oasis                         116
Radiating Aztec                    103
Burnished Lilac                    101
Sterling Pewter with Solid Lace     90
Cadette Green with Solid Lace       88
Rosy Mauve with Solid Lace          87
Silver Sea with Solid Lace          84
Lip Smacker with Solid Lace         84
coconut white                       70
black                               68
ensign blue                         40
cadette green                       40
faded denim                         30
ruby wine                           30
silver sea floral print             30
champagne floral print              30
ensign                              16
starlet pink marl                   15
powder blush                        15
black diamond squares print         15
smokey pearl marl                   15
black overt marl                    15
coconut white geo squares print     15
nude                                15
plum dust                           15
champagne                           15
peach melba                         13
chintz rose                         12
evening blush                       10
black marl                           9
summer floral print                  8
floral wave print                    8
gold wave print                      8
ginger glaze                         8
blue wave print                      8
rosy mauve                           7
indigo summer print                  7
fair orchid                          5
Coconut White                        5
Teak                                 5
Fir                                  5
clay grey                            4
pure black                           3
light pink                           3
triumph white                        3
blue                                 3
coconut waters                       1
Name: color, dtype: int64

In [ ]:
df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'].value_counts()

Victoria Sport NEW! Lightweight by Victoria Sport Strappy Sport Bra    117
Dream Angels Lace-Trim Thong Panty                                      14
Very Sexy NEW! Plunge Lace-up Teddy                                     10
Dream Angels NEW! Racerback Lace Bodysuit                               10
Very Sexy Chiffon Cami & Short Set                                       9
Dream Angels NEW! Lace & Mesh Cheekini Panty                             8
Very Sexy Lace & Mesh Thong Panty                                        8
Very Sexy NEW! XO V-string Panty                                         5
Very Sexy NEW! Lace-up High-neck Bra                                     5
Very Sexy Satin Cami & Short Set                                         4
Name: product_name, dtype: int64

In [ ]:
len(df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'])

190

In [ ]:
top_rating = df['rating'].max()
df_5 = df.loc[df['rating'] == top_rating]
top_rating, len(df_5)

(5.0, 1499)

In [ ]:
df_5['product_name'].value_counts()

Victoria Sport NEW! Lightweight by Victoria Sport Strappy Sport Bra    437
Dream Angels Demi Bra                                                  433
Body by Victoria Demi Bra                                              180
Everyday Perfect NEW! Hipster Panty                                     99
Everyday Perfect NEW! Textured Curved-hem Thong Panty                   57
Cotton Lingerie Mesh Thong Panty                                        39
Dream Angels NEW! Lace & Mesh Cheekini Panty                            36
Very Sexy Lace & Mesh Thong Panty                                       33
Dream Angels NEW! Racerback Lace Bodysuit                               30
Very Sexy NEW! Plunge Lace-up Teddy                                     30
Very Sexy Chiffon Cami & Short Set                                      25
Dream Angels Lace-Trim Thong Panty                                      24
Very Sexy NEW! XO V-string Panty                                        21
Very Sexy NEW! Lace-up High-neck Bra                                    20
Very Sexy Satin Cami & Short Set                                        18
PINK NEW! Cropped Raglan Full-Zip                                       16
PINK Coconut Waters Travel Kit                                           1
Name: product_name, dtype: int64

In [ ]:
df_5['color'].value_counts()

Black                              122
Grey Oasis                         116
Radiating Aztec                    103
Burnished Lilac                    101
Sterling Pewter with Solid Lace     90
Cadette Green with Solid Lace       88
Rosy Mauve with Solid Lace          87
Silver Sea with Solid Lace          84
Lip Smacker with Solid Lace         84
coconut white                       70
black                               68
ensign blue                         40
cadette green                       40
faded denim                         30
ruby wine                           30
silver sea floral print             30
champagne floral print              30
ensign                              16
starlet pink marl                   15
powder blush                        15
black diamond squares print         15
smokey pearl marl                   15
black overt marl                    15
coconut white geo squares print     15
nude                                15
plum dust                           15
champagne                           15
peach melba                         13
chintz rose                         12
evening blush                       10
black marl                           9
summer floral print                  8
floral wave print                    8
gold wave print                      8
ginger glaze                         8
blue wave print                      8
rosy mauve                           7
indigo summer print                  7
fair orchid                          5
Coconut White                        5
Teak                                 5
Fir                                  5
clay grey                            4
pure black                           3
light pink                           3
triumph white                        3
blue                                 3
coconut waters                       1
Name: color, dtype: int64

In [ ]:
df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'].value_counts()

Victoria Sport NEW! Lightweight by Victoria Sport Strappy Sport Bra    117
Dream Angels Lace-Trim Thong Panty                                      14
Very Sexy NEW! Plunge Lace-up Teddy                                     10
Dream Angels NEW! Racerback Lace Bodysuit                               10
Very Sexy Chiffon Cami & Short Set                                       9
Dream Angels NEW! Lace & Mesh Cheekini Panty                             8
Very Sexy Lace & Mesh Thong Panty                                        8
Very Sexy NEW! XO V-string Panty                                         5
Very Sexy NEW! Lace-up High-neck Bra                                     5
Very Sexy Satin Cami & Short Set                                         4
Name: product_name, dtype: int64

In [ ]:
len(df_5[(df_5['color'] == 'Black') | (df_5['color'] == 'black')]['product_name'])

190